services:
  web:
    build: .
    ports:
      - "5001:5000"
    command: ["./wait-for-it.sh", "db:3306", "--", "python", "app.py"]  

    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=my_password
      - MYSQL_DB=TestDB
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
    depends_on:
      - db

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my_password
      MYSQL_DATABASE: TestDB
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data: